package com.struts2.util.mapping;
// Generated Sep 24, 2020 3:50:11 PM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Onlineaccount generated by hbm2java
 */
@Entity
@Table(name="onlineaccount")
public class Onlineaccount  implements java.io.Serializable {


     private Integer userId;
     private String userName;
     private String mobileNumber;
     private String gender;
     private String password;

    public Onlineaccount() {
    }

    public Onlineaccount(String userName, String mobileNumber, String gender, String password) {
       this.userName = userName;
       this.mobileNumber = mobileNumber;
       this.gender = gender;
       this.password = password;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="user_id", unique=true, nullable=false)
    public Integer getUserId() {
        return this.userId;
    }
    
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    
    @Column(name="user_name", nullable=false, length=20)
    public String getUserName() {
        return this.userName;
    }
    
    public void setUserName(String userName) {
        this.userName = userName;
    }

    
    @Column(name="mobile_number", nullable=false, length=10)
    public String getMobileNumber() {
        return this.mobileNumber;
    }
    
    public void setMobileNumber(String mobileNumber) {
        this.mobileNumber = mobileNumber;
    }

    
    @Column(name="gender", nullable=false, length=10)
    public String getGender() {
        return this.gender;
    }
    
    public void setGender(String gender) {
        this.gender = gender;
    }

    
    @Column(name="password", nullable=false)
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }




}


